version: "3.7"

services:

  app:
    container_name: api-doeobem-feed
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - 8015:80
    environment:
      # Variáveis de ambiente para PHP (opcional, mas recomendado)
      PHP_UPLOAD_MAX_FILESIZE: 100M
      PHP_POST_MAX_SIZE: 100M
      PHP_MEMORY_LIMIT: 300M
    networks:
      - api-doeobem

networks:
  api-doeobem:
    external: true


